name: Deploy Image Processing Job

on:
  workflow_dispatch:

env:
  JOB_NAME: image-processing-service
  GAR_LOCATION: ${{ secrets.GCP_REGION }}
  GAR_REPOSITORY: histopath-docker-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
            --image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.JOB_NAME }}:latest \
            --region=${{ secrets.GCP_REGION }} \
            --add-volume=name=input-bucket,type=cloud-storage,bucket=${{ secrets.GCS_ORIGINAL_BUCKET_NAME }},readonly=true \
            --add-volume=name=output-bucket,type=cloud-storage,bucket=${{ secrets.GCS_PROCESSED_BUCKET_NAME }} \
            --add-volume-mount=volume=input-bucket,mount-path="/gcs/${{ secrets.GCS_ORIGINAL_BUCKET_NAME }}" \
            --add-volume-mount=volume=output-bucket,mount-path="/gcs/${{ secrets.GCS_PROCESSED_BUCKET_NAME }}" \
            --update-env-vars="APP_ENV=PROD" \
            --update-env-vars="PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --update-env-vars="GCS_ORIGINAL_BUCKET_NAME=${{ secrets.GCS_ORIGINAL_BUCKET_NAME }}" \
            --update-env-vars="GCS_PROCESSED_BUCKET_NAME=${{ secrets.GCS_PROCESSED_BUCKET_NAME }}" \
            --update-env-vars="IMAGE_PROCESSING_SUB_ID=${{ secrets.GCP_IMAGE_PROCESSING_SUB_ID }}" \
            --update-env-vars="IMAGE_PROCESS_RESULT_TOPIC_ID=${{ secrets.GCP_IMAGE_PROCESS_RESULT_TOPIC_ID }}" \
            --update-env-vars="INPUT_MOUNT_PATH=/gcs/${{ secrets.GCS_ORIGINAL_BUCKET_NAME }}" \
            --update-env-vars="OUTPUT_MOUNT_PATH=/gcs/${{ secrets.GCS_PROCESSED_BUCKET_NAME }}" \
            --update-env-vars="LOG_LEVEL=INFO" \
            --update-env-vars="LOG_FORMAT=json" \
            --update-env-vars="TILE_SIZE=256" \
            --update-env-vars="OVERLAP=0" \
            --update-env-vars="QUALITY=85" \
            --update-env-vars="DZI_LAYOUT=dz" \
            --update-env-vars="DZI_SUFFIX=jpeg" \
            --update-env-vars="THUMBNAIL_SIZE=256" \
            --update-env-vars="THUMBNAIL_QUALITY=90"

      - name: Install Beta and Update Eventarc Trigger
        run: |
          gcloud components install beta --quiet
          
          gcloud events triggers update image-processor-trigger \
            --location=${{ secrets.GCP_REGION }} \
            --destination-run-job=${{ env.JOB_NAME }} \
            --destination-run-region=${{ secrets.GCP_REGION }} \
            --event-filters="type=google.cloud.pubsub.topic.v1.messagePublished" \
            --transport-topic=${{ secrets.GCP_SOURCE_TOPIC_ID }} \
            --transport-topic=${{ secrets.GCP_IMAGE_PROCESSING_TOPIC_ID }}
