name: Build and Deploy Image Processing Service

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  SERVICE_NAME: image-processing-service
  GAR_LOCATION: ${{ secrets.GCP_REGION }}
  GAR_REPOSITORY: histopath-docker-repo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 
    
    outputs:
      image_tag: ${{ steps.build-push.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        id: build-push
        run: |
          IMAGE_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          IMAGE_LATEST="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:latest"
          
          docker build -t $IMAGE_TAG -t $IMAGE_LATEST .
          docker push $IMAGE_TAG
          docker push $IMAGE_LATEST
          
          # Deploy job'unun kullanması için imaj etiketini 'output' olarak ayarla
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build # 
    permissions:
      id-token: write 
      
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gcloud Beta Components
        run: |
          gcloud components install beta --quiet

      - name: Deploy to Cloud Run Service
        run: |
          gcloud beta run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ needs.build.outputs.image_tag }} \
            --region=${{ secrets.GCP_REGION }} \
            --generation=gen2 \
            --service-account=${{ secrets.GCP_RUN_SERVICE_ACCOUNT_EMAIL }} \
            --no-allow-unauthenticated \
            --min-instances=0 \
            --max-instances=5 \
            --add-gcs-bucket="bucket=${{ secrets.GCS_ORIGINAL_BUCKET_NAME }},read-only=true" \
            --add-gcs-bucket="bucket=${{ secrets.GCS_PROCESSED_BUCKET_NAME }},read-write=true" \
            --update-env-vars="APP_ENV=PROD" \
            --update-env-vars="PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --update-env-vars="GCS_ORIGINAL_BUCKET_NAME=${{ secrets.GCS_ORIGINAL_BUCKET_NAME }}" \
            --update-env-vars="GCS_PROCESSED_BUCKET_NAME=${{ secrets.GCS_PROCESSED_BUCKET_NAME }}" \
            --update-env-vars="IMAGE_PROCESSING_SUB_ID=${{ secrets.GCP_IMAGE_PROCESSING_SUB_ID }}" \
            --update-env-vars="IMAGE_PROCESS_RESULT_TOPIC_ID=${{ secrets.GCP_IMAGE_PROCESS_RESULT_TOPIC_ID }}" \
            --update-env-vars="INPUT_MOUNT_PATH=/gcs/${{ secrets.GCS_ORIGINAL_BUCKET_NAME }}" \
            --update-env-vars="OUTPUT_MOUNT_PATH=/gcs/${{ secrets.GCS_PROCESSED_BUCKET_NAME }}" \
            --update-env-vars="LOG_LEVEL=INFO" \
            --update-env-vars="LOG_FORMAT=json" \
            --update-env-vars="TILE_SIZE=256" \
            --update-env-vars="OVERLAP=0" \
            --update-env-vars="QUALITY=85" \
            --update-env-vars="DZI_LAYOUT=dz" \
            --update-env-vars="DZI_SUFFIX=jpeg" \
            --update-env-vars="THUMBNAIL_SIZE=256" \
            --update-env-vars="THUMBNAIL_QUALITY=90"